name: Build and Publish
on:
  push:
    branches:
      - main
  pull_request:
jobs:
    test:
        name: "Run tests"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Install tools
              uses: asdf-vm/actions/install@v3

            - name: Run tests
              run: pkl test tests.pkl
    build_and_publish:
        name: "Create Pkl package, tag and release"
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
    
            - name: Install tools
              uses: asdf-vm/actions/install@v3
    
            - name: Determine version bump level
              id: determine_bump_level
              run: echo "level=patch" >> $GITHUB_ENV

            - name: Get Current Version
              id: get_version
              run: echo "current_version=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

            - name: Calculate next version
              id: get_semver
              uses: rickstaa/action-get-semver@v1
              with:
                bump_level: ${{ env.level }}
            
            - name: Set Project Version Output
              id: project_version
              run: |
                echo "project_version=${{ steps.get_semver.outputs.next_version }}" >> $GITHUB_ENV
                echo "project_version_without_v=$(echo ${{ steps.get_semver.outputs.next_version }} |  tr -d 'v')" >> $GITHUB_ENV
                echo "pkl_version_tag=terraform@$(echo ${{ steps.get_semver.outputs.next_version }} |  tr -d 'v')" >> $GITHUB_ENV
            
            - name: Substitute version
              run: |
                sed -i "s/0.0.0/${{ env.project_version_without_v }}/g" PklProject

            - name: Build Pkl package
              run: pkl project package

            - name: Apply tag
              run : git tag ${{ env.project_version }}
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'

            - name: Apply Pkl tag
              run : git tag ${{ env.pkl_version_tag }}
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'

            - name: Release
              uses: softprops/action-gh-release@v2
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              with:
                tag_name: ${{ env.pkl_version_tag}}
                files: .out/terraform@${{env.project_version_without_v}}/*

            - name: Push tags
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: git push origin ${{ env.project_version }}